name: Translate docs

on:
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: List changed files
        run: |
          echo "Changed files between main and ${{ github.ref_name }}:"
          echo "------------------------------------------------------"
          git diff --name-only main..${{ github.ref_name }}